### PR TITLE
[fix] command `/list`

### LINKED ISSUE #33: [bug] Telegram API limits messages to 4096 characters
Because of this limitation, large messages as the one we can get with the `/all` command are blocked.

In order that clients receive the information, large message have to be splitted.

### PR DESCRIPTION
**Pull request by SaphireVert**
- fix #33

### CODE REVIEW

File: lib/Commands.js [hunk 1]
```diff
@@ -45,18 +45,29 @@ class Commands {
...
-        console.log(messageFinal)
-        // return this.bot.sendMessage(msg.chat.id, messageFinal, {parseMode: 'Markdown'});
+        messages.push(message)
+        for await (let element of messages) {
+            await this.bot.sendMessage(msg.chat.id, element, {parseMode: 'Markdown'})
+        }
     }
     all(msg){this.list(msg)}
     listall(msg){this.list(msg)}
+    commandes(msg){this.list(msg)}
```
Comment (ponsfrilus) [inline lib/Commands.js:70]: If this command is necessary, please add it to /help

**Review by ponsfrilus — APPROVED** [review]
LGTM
